/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SeminariaRouteImport } from './routes/seminaria'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ViografikoRouteImport } from './routes/viografiko'
import { Route as AsSxoliasoumeIndexRouteImport } from './routes/as-sxoliasoume/index'
import { Route as AsSxoliasoumeSlugRouteImport } from './routes/as-sxoliasoume/$slug'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesSlugRouteImport } from './routes/services/$slug'
import { Route as YpiresiesIndexRouteImport } from './routes/ypiresies.index'
import { Route as YpiresiesServiceIdRouteImport } from './routes/ypiresies.$serviceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SeminariaRoute = SeminariaRouteImport.update({
  id: '/seminaria',
  path: '/seminaria',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ViografikoRoute = ViografikoRouteImport.update({
  id: '/viografiko',
  path: '/viografiko',
  getParentRoute: () => rootRouteImport,
} as any)
const AsSxoliasoumeIndexRoute = AsSxoliasoumeIndexRouteImport.update({
  id: '/as-sxoliasoume/',
  path: '/as-sxoliasoume/',
  getParentRoute: () => rootRouteImport,
} as any)
const AsSxoliasoumeSlugRoute = AsSxoliasoumeSlugRouteImport.update({
  id: '/as-sxoliasoume/$slug',
  path: '/as-sxoliasoume/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const YpiresiesIndexRoute = YpiresiesIndexRouteImport.update({
  id: '/ypiresies/',
  path: '/ypiresies/',
  getParentRoute: () => rootRouteImport,
} as any)
const YpiresiesServiceIdRoute = YpiresiesServiceIdRouteImport.update({
  id: '/ypiresies/$serviceId',
  path: '/ypiresies/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/seminaria': typeof SeminariaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/viografiko': typeof ViografikoRoute
  '/as-sxoliasoume/$slug': typeof AsSxoliasoumeSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/ypiresies/$serviceId': typeof YpiresiesServiceIdRoute
  '/as-sxoliasoume/': typeof AsSxoliasoumeIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/ypiresies/': typeof YpiresiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/seminaria': typeof SeminariaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/viografiko': typeof ViografikoRoute
  '/as-sxoliasoume/$slug': typeof AsSxoliasoumeSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/ypiresies/$serviceId': typeof YpiresiesServiceIdRoute
  '/as-sxoliasoume': typeof AsSxoliasoumeIndexRoute
  '/services': typeof ServicesIndexRoute
  '/ypiresies': typeof YpiresiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/seminaria': typeof SeminariaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/viografiko': typeof ViografikoRoute
  '/as-sxoliasoume/$slug': typeof AsSxoliasoumeSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/ypiresies/$serviceId': typeof YpiresiesServiceIdRoute
  '/as-sxoliasoume/': typeof AsSxoliasoumeIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/ypiresies/': typeof YpiresiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/privacy'
    | '/seminaria'
    | '/sitemap.xml'
    | '/terms'
    | '/viografiko'
    | '/as-sxoliasoume/$slug'
    | '/services/$slug'
    | '/ypiresies/$serviceId'
    | '/as-sxoliasoume/'
    | '/services/'
    | '/ypiresies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/privacy'
    | '/seminaria'
    | '/sitemap.xml'
    | '/terms'
    | '/viografiko'
    | '/as-sxoliasoume/$slug'
    | '/services/$slug'
    | '/ypiresies/$serviceId'
    | '/as-sxoliasoume'
    | '/services'
    | '/ypiresies'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/privacy'
    | '/seminaria'
    | '/sitemap.xml'
    | '/terms'
    | '/viografiko'
    | '/as-sxoliasoume/$slug'
    | '/services/$slug'
    | '/ypiresies/$serviceId'
    | '/as-sxoliasoume/'
    | '/services/'
    | '/ypiresies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  SeminariaRoute: typeof SeminariaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ViografikoRoute: typeof ViografikoRoute
  AsSxoliasoumeSlugRoute: typeof AsSxoliasoumeSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  YpiresiesServiceIdRoute: typeof YpiresiesServiceIdRoute
  AsSxoliasoumeIndexRoute: typeof AsSxoliasoumeIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  YpiresiesIndexRoute: typeof YpiresiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seminaria': {
      id: '/seminaria'
      path: '/seminaria'
      fullPath: '/seminaria'
      preLoaderRoute: typeof SeminariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viografiko': {
      id: '/viografiko'
      path: '/viografiko'
      fullPath: '/viografiko'
      preLoaderRoute: typeof ViografikoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/as-sxoliasoume/': {
      id: '/as-sxoliasoume/'
      path: '/as-sxoliasoume'
      fullPath: '/as-sxoliasoume/'
      preLoaderRoute: typeof AsSxoliasoumeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/as-sxoliasoume/$slug': {
      id: '/as-sxoliasoume/$slug'
      path: '/as-sxoliasoume/$slug'
      fullPath: '/as-sxoliasoume/$slug'
      preLoaderRoute: typeof AsSxoliasoumeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ypiresies/': {
      id: '/ypiresies/'
      path: '/ypiresies'
      fullPath: '/ypiresies/'
      preLoaderRoute: typeof YpiresiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ypiresies/$serviceId': {
      id: '/ypiresies/$serviceId'
      path: '/ypiresies/$serviceId'
      fullPath: '/ypiresies/$serviceId'
      preLoaderRoute: typeof YpiresiesServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  SeminariaRoute: SeminariaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ViografikoRoute: ViografikoRoute,
  AsSxoliasoumeSlugRoute: AsSxoliasoumeSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  YpiresiesServiceIdRoute: YpiresiesServiceIdRoute,
  AsSxoliasoumeIndexRoute: AsSxoliasoumeIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  YpiresiesIndexRoute: YpiresiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
